### PR TITLE
Fix Incorrect RegEx for Israel

### LINKED ISSUE #31: Incorrect RegEx for Israel
Hi,

i justnoticed that the postcode validation reg ex for israel (il) is wrong. 
Israel can also have 7 (new) digit post codes and not only 5 (old). So it would be better to support both.

https://en.wikipedia.org/wiki/Postal_codes_in_Israel

Greetings
DosOvO

### PR DESCRIPTION
**Pull request by DosOvO**
This PR fixes #31

### CODE REVIEW

**Review by sarcadass — APPROVED** [review]

**Comment by sarcadass** [comment]
Thank you for the PR, it seems that Travis CI is not responding. 😢
I'll check what's wrong soon.

**Comment by sarcadass** [comment]
Hello @DosOvO 
I replaced TravisCI by Github Actions.
Can you please rebase your branch on up-to-date `master` and push your branch back.
This will allow the PR to run the new CI checks.
Thank you.

**Comment by DosOvO** [comment]
Hello @sarcadass,

done

**Review by sarcadass — APPROVED** [review]

**Comment by sarcadass** [comment]
These changes are now available in the latest release `v5.0.0`.
Thank you for opening this PR.

**Pull request merged**
